- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Update apt cache
  apt:
    update_cache: yes


- name: Download kubectl
  get_url:
    url: "https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl"
    dest: /usr/bin/kubectl
    mode: '0755'

- name: Download Minikube binary
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/bin/minikube
    mode: '0755'

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "ubuntu"
    groups: docker
    append: yes

- name: Start Minikube with docker driver
  command: minikube start --driver=docker
  become: yes
  become_user: ubuntu
  environment:
    HOME: "/home/ubuntu"
  register: minikube_start
  changed_when: minikube_start.rc == 0
  failed_when: false