apiVersion: v1
kind: Service
metadata:
  name: ivolve-service
spec:
  type: NodePort
  selector:
    app: ivolve
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001